from typing import Protocol

from app.domain.models import CheckResult, Monitor


class MonitorRepository(Protocol):
    async def create(self, monitor: Monitor) -> Monitor: ...
    async def list_monitors(self) -> list[Monitor]: ...
    async def get(self, monitor_id: str) -> Monitor | None: ...
    async def update(self, monitor_id: str, changes: dict) -> Monitor | None: ...
    async def delete(self, monitor_id: str) -> bool: ...
    async def add_result(self, result: CheckResult) -> CheckResult: ...
    async def result_exists(self, monitor_id: str, job_id: str) -> bool: ...
    async def list_results(self, monitor_id: str) -> list[CheckResult]: ...
    async def ready(self) -> bool: ...
